version: '3.4'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "9001:80"
    volumes:
      - ./:/var/www/html/payment_api/
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./vendor/:/var/www/html/payment_api/vendor/
    depends_on: 
      - php-fpm

  php-fpm:
    build: ./docker/
    container_name: php-container
    links: 
      - mysql
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_HOSTNAME=mysql
      - DB_DATABASE=payment_api
      - DB_USERNAME=root
      - DB_PASSWORD=

    volumes:
     - ./:/var/www/html/payment_api/
     - ./docker/www.conf:/etc/php5/fpm/pool.d/www.conf

  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - 3307:3306 
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: payment_api
      MYSQL_USER: root  
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - data:/var/lib/mysql

volumes:
  data: