slim:
  image: sinuraya/slim-php7:latest
  ports:
      - "9001:80"
  volumes:
    - ./:/var/www/html/payment_api/
    - ./vendor/:/var/www/html/payment_api/vendor/
    - ./httpd.conf:/etc/apache2/sites-enabled/httpd.conf
  environment:
    APPLICATION_ENV: local
