version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "9001:80"
    volumes:
      - ./:/var/www/html/payment_api/
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./vendor/:/var/www/html/payment_api/vendor/
    depends_on: 
      - php-fpm

  php-fpm:
    build: ./docker/
    container_name: php-container
    links:
      - mysql
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_HOST=localhost
      - DB_NAME=payment_api
      - DB_USER=root
      - DB_PASS=

    volumes:
     - ./:/var/www/html/payment_api/
     - ./docker/www.conf:/etc/php5/fpm/pool.d/www.conf

  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: payment_api
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - my-data:/var/lib/mysql

volumes:
  my-data:
